### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by IVEmmaWatson** [Sigurd015/Sekirolike#1]
hello Teacher，i'm a soul game funs also a new UE5 developer, and i want to study how to create a sekiro like game demo , but download this project and open in Uengine has  problem,"the game module 'sekirolike could not be found ,please ensure that this module exists and that it is compiled'"
So I sincerely ask you to help me this

**Comment by IVEmmaWatson** [comment]
I have solved the problem，there is new problem is i run this level and control character move,but cant attack or play other animation, likes mouse key just print debug message "play attack montage"

**Comment by Sigurd015** [comment]
Currently, this project is unfinished, I recommend this tutorial [Unreal Engine 5 C++: Advanced Action RPG](https://www.udemy.com/course/unreal-engine-5-advanced-action-rpg/?couponCode=V2JPLETSLEARN)
